#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

## lang
export LANG=ja_JP.UTF-8

## enable showing multi byte language
setopt print_eight_bit

## color
autoload -Uz colors
colors

bindkey -e

## history
HISTFILE=~/.zsh_history
HISTSIZE=1000000
SAVEHIST=1000000
setopt hist_no_store
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_reduce_blanks
setopt share_history

## prompt
PROMPT="
%{${fg[green]}%}[%n@%m]%{${reset_color}%} 
%~
%# "

## word style
autoload -Uz select-word-style
select-word-style default
zstyle ':zle:*' word-chars " /=;@:{},|"
zstyle ':zle:*' word-style unspecified

## completion

### zsh-completions
if [ -e /usr/local/share/zsh-completions ]; then
  fpath=(/usr/local/share/zsh-completions $fpath)
fi
autoload -U compinit
compinit -u

zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z} r:|[-_.]=**'
zstyle ':completion:*:processes' menu yes select=2
zstyle ':completion:*' ignore-parents parent pwd ..
zstyle ':completion:*:sudo:*' command-path /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/X11R6/bin
zstyle ':completion:*:processes' command 'ps x -o pid,s,args'

## vcs_info setting
autoload -Uz vcs_info
autoload -Uz add-zsh-hook

zstyle ':vcs_info:*' formats '%F{green}(%s)-[%b]%f'
zstyle ':vcs_info:*' actionformats '%F{red}(%s)-[%b|%a]%f'

function _update_vcs_info_msg() {
  LANG=en_US.UTF-8 vcs_info
  RPROMPT="${vcs_info_msg_0_}"
}
add-zsh-hook precmd _update_vcs_info_msg

## disable beep 
setopt no_beep

## disable flow control by Ctrl+S/Ctrl+Q 
setopt no_flow_control

## disable stop by Ctrl+D
setopt ignore_eof

## '#' 以降をコメントとして扱う
setopt interactive_comments

## ディレクトリ名だけでcdする
setopt auto_cd
setopt cdable_vars

## cd したら自動的にpushdする
setopt auto_pushd
## 重複したディレクトリを追加しない
setopt pushd_ignore_dups

# peco setting

## histories
function peco-select-history() {
  local tac
  if which tac > /dev/null; then
    tac="tac"
  else
    tac="tail -r"
  fi
  BUFFER=$(\history -n 1 | \
  eval $tac | \
  peco --query "$LBUFFER")
  CURSOR=$#BUFFER
  zle clear-screen
}
zle -N peco-select-history
bindkey '^r' peco-select-history

## ghq
function peco-ghq-look () {
  local selected_file=$(ghq list --full-path | peco --query "$LBUFFER")
  if [ -n "$selected_file" ]; then
    if [ -t 1 ]; then
      echo ${selected_file}
      cd ${selected_file}
      pwd
    fi
  fi
}
zle -N peco-ghq-look
bindkey '^G' peco-ghq-look

# 高機能なワイルドカード展開を使用する
setopt extended_glob

# key bindings

# aliases

alias la='ls -la'
alias ll='ls -la'

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# auto cd
setopt auto_cd
function chpwd() { ls -la }

# enable cdr, add-zsh-hook
autoload -Uz chpwd_recent_dirs cdr add-zsh-hook add-zsh-hook chpwd chpwd_recent_dirs

# cdr setting
zstyle ':completion:*' recent-dirs-insert both
zstyle ':completion:*:*:cdr:*:*' menu selection
zstyle ':chpwd:*' recent-dirs-max 500
zstyle ':chpwd:*' recent-dirs-default true
zstyle ':chpwd:*' recent-dirs-file "$HOME/.cache/shell/chpwd-recent-dirs"
zstyle ':chpwd:*' recent-dirs-pushd true

# vim:set ft=zsh:

# xxenv setting
eval "$(rbenv init -)"
export PATH="$HOME/.rbenv/bin:$PATH"

if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
if which plenv > /dev/null; then eval "$(plenv init -)"; fi
if which goenv > /dev/null; then eval "$(goenv init -)"; fi
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
if which ndenv > /dev/null; then eval "$(ndenv init -)"; fi

export HOMEBREW_CASK_OPTS="--appdir=/Applications"
